name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main

  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    - name: Setup GitHub Pages
      id: setup
      uses: actions/configure-pages@v2
      # with:
      #   static_site_generator: sveltekit
      #   generator_config_file: vite.config.js

    - name: Install dependencies
      run: npm ci

    - name: Build with SvelteKit
      run: npm run build
      env:
        BASE_URI: ${{ steps.setup.outputs.base_url }}/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: dist

  deploy:
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
